### PR TITLE
Delay extraction directory creation to just before messages are sent

### LINKED ISSUE #913: Delay creation of extraction directory until user confirms the settings
https://github.com/SMI/SmiServices/blob/47763734f4d2aafce2137712ff4a690fe16e29c8/src/applications/Applications.ExtractImages/ExtractImagesHost.cs#L64

Currently if you attempt to start an extraction, cancel at the prompt, and try to re-run, this crashes since the extraction directory is eagerly created.

### PR DESCRIPTION
**Pull request by rkm**
## Proposed Changes

Fix #913 by delaying the directory creation step.

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [x] Updated any relevant API documentation
- [x] Created or updated any tests if relevant
- [x] Created a [news](https://github.com/SMI/SmiServices/blob/master/news/README.md) file
    -   NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues

- Closes #913.

### CODE REVIEW

File: src/applications/Applications.ExtractImages/ExtractImagesHost.cs [hunk 1]
```diff
@@ -56,12 +58,10 @@ public class ExtractImagesHost : MicroserviceHost
...
             string extractionDir = _fileSystem.Path.Join(cliOptions.ProjectId, "extractions", extractionName);
-            string absoluteExtractionDir = _fileSystem.Path.Join(extractRoot, extractionDir);
-
-            if (_fileSystem.Directory.Exists(absoluteExtractionDir))
-                throw new DirectoryNotFoundException($"Extraction directory already exists '{absoluteExtractionDir}'");
+            _absoluteExtractionDir = _fileSystem.Path.Join(extractRoot, extractionDir);
 
-            _fileSystem.Directory.CreateDirectory(absoluteExtractionDir);
+            if (_fileSystem.Directory.Exists(_absoluteExtractionDir))
+                throw new DirectoryNotFoundException($"Extraction directory already exists '{_absoluteExtractionDir}'");
```
Comment (tznind) [inline src/applications/Applications.ExtractImages/ExtractImagesHost.cs:64]: Surely if the file is empty that would be ok? Is this to prevent multiple extractions overwritting each other?

File: src/applications/Applications.ExtractImages/ExtractImagesHost.cs [hunk 2]
```diff
@@ -90,7 +91,7 @@ public override void Start()
             var parser = new CohortCsvParser(_fileSystem);
             (ExtractionKey extractionKey, List<string> idList) = parser.Parse(_csvFilePath);
 
-            _extractionMessageSender.SendMessages(extractionKey, idList);
+            _extractionMessageSender.SendMessages(_absoluteExtractionDir, extractionKey, idList);
```
Comment (tznind) [inline src/applications/Applications.ExtractImages/ExtractImagesHost.cs:94]: Why do we pass the dir to `_extractionMessageSender`? Seems like a lot of code change in this PR is to allow the directory creation to happen in the `ExtractionMessageSender` class instead of  `ExtractImageHost`.  Whats the logic behind moving it?

**Review by tznind — CHANGES_REQUESTED** [review]

File: src/applications/Applications.ExtractImages/ExtractImagesHost.cs (hunk 1 above)
Comment (rkm) [reply src/applications/Applications.ExtractImages/ExtractImagesHost.cs:64]: Yep, this is to prevent any file clobbering.

File: src/applications/Applications.ExtractImages/ExtractImagesHost.cs (hunk 2 above)
Comment (rkm) [reply src/applications/Applications.ExtractImages/ExtractImagesHost.cs:94]: This solves #913 by moving the directory creation to after the confirmation prompt. The `SendMessages` function is currently the most obvious place to put that. The next PR #915 actually simplifies this further, so I'm not too worried about things looking perfect here.

Comment (tznind) [reply src/applications/Applications.ExtractImages/ExtractImagesHost.cs:94]: ok if it is  changing in the next PR anyway can go with it.

**Review by tznind — APPROVED** [review]
